# Generated by Django 4.2.4 on 2023-08-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('customer_type', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('product_line', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('tax_5_percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('payment', models.CharField(max_length=100)),
                ('cogs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_margin_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gross_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
